services:
  # PostgreSQL servisi
  db:
    image: postgres:latest
    container_name: postgres-db
    restart: always  
    environment:
      POSTGRES_DB: bank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  # FastAPI servisi
  app:
    build: .
    container_name: fastapi-app
    restart: always 
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:12345@db:5432/bank
    volumes:
      - ./src:/app/src  # Uygulama dosyalarını /app dizinine kopyalıyoruz
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge